Update for unification of monitor processing
neutrinolabs/xorgxrdp pull request #212
Opened 2022-03-21 00:11 UTC by Nexarian

Related to https://github.com/neutrinolabs/xrdp/pull/1895. Need to update to reflect the changes to xrdp_client_info.h

2022-03-21 00:17 UTC, aquesnel approved these changes

2022-03-21 00:24 UTC, Nexarian commented
@matt335672 @metalefty  I'm not sure why the build checks fail. The probably will because of the dependency on xrdp, but additionally, it looks like something is wrong with the build environment. Embarrassingly, I also can't find the "retry/re-run" option.

2022-03-21 00:38 UTC, Nexarian commented
Ah I figured it out. Also needed this: https://github.com/neutrinolabs/xrdp/commit/341a32581cb902c49cb557c956d754c912a31d6e

2022-03-21 00:59 UTC, Nexarian commented
Decided to separate out the fix for the checks to keep the commits more atomic: https://github.com/neutrinolabs/xorgxrdp/pull/213

2022-03-21 10:33 UTC, matt335672 commented
Hi @Nexarian 

I've pulled your other fix in, so if you re-base this it should get through the CI now.

2022-03-21 14:35 UTC, Nexarian commented
@matt335672 It now fails as expected!

2022-03-22 09:50 UTC, matt335672 commented
That's fine - we can merge this at the same time as the other changes in neutrinolabs/xrdp#1895.

2022-03-24 08:20 UTC, metalefty requested changes

2022-03-24 08:20 UTC, metalefty commented on module/rdpClientCon.c
> +    if (clientCon->client_info.display_sizes.monitorCount > 0)
Can you keep compatibility with older versions of xrdp? Probably using some macros and check `CLIENT_INFO_CURRENT_VERSION`.

This is not always necessary but I want that at this time.

2022-03-27 20:48 UTC, Nexarian commented
@matt335672 @metalefty Take another look, and hopefully this can be merged along with https://github.com/neutrinolabs/xrdp/pull/1895

2022-03-28 07:29 UTC, metalefty approved these changes

2022-03-28 17:43 UTC, matt335672 commented
That'll work, and I'm sort of Okay with it, but rather than having three explicit checks against `CLIENT_INFO_CURRENT_VERSION`, it might be better to add a level of indirection:-

```c
/* See <add suitable reference> */
#if CLIENT_INFO_CURRENT_VERSION > 20210723
#   define CLIENT_INFO_HAS_DISPLAY_SIZES
#endif
```

then :-

```c
#if CLIENT_INFO_HAS_DISPLAY_SIZES
    if (clientCon->client_info.display_sizes.monitorCount > 0)
#else
    if (clientCon->client_info.monitorCount > 0)
#endif
```

etc.

What do people think? Is that overthinking it?

2022-03-28 18:16 UTC, Nexarian commented
I believe it is overthinking it, largely because:
1. We do not generally intend to have xorgxrdp be backwards compatible. This is a specific, bespoke, one-off request from @metalefty that I believe will be short term.
2. If we DO intend for xorgxrdp to be backwards compatible with varying versions of XRDP, that is a much bigger conversation, and neither what I've written here nor what you propose would be sufficient to deal with that.

My change is a surgical fix to directly fix this issue, and only that. Doing more risks moving the surgery from "minimally invasive" to "actually invasive."

I also expect/suspect we'd want to remove this fix when the next release happens, and this is here only for the interim.

2022-03-28 18:23 UTC, matt335672 commented
OK - that's fine. You've convinced me.

Do you want to add a comment somewhere along those lines? The comment will obviously also be deleted when we remove this fix!

2022-03-28 20:00 UTC, Nexarian commented
@matt335672 Alright, updated. See the issue I've linked to!

2022-03-29 08:11 UTC, merged

2022-03-29 08:31 UTC, matt335672 commented
@Nexarian, @metalefty - I've added an additional Wiki page for xorgxrdp here:-

https://github.com/neutrinolabs/xorgxrdp/wiki/NEWS

This serves the same purpose as the [NEWS page for xrdp](https://github.com/neutrinolabs/xrdp/wiki/NEWS). We can collect the merged changes as we go along so it makes the actual release process easier.